### ISSUE TITLE
Paths resolution

### ISSUE THREAD

**Issue by Satont** [code-withAshish/grammy-cli#3]
https://github.com/code-withAshish/grammy-cli/blob/437f6a22d4ea945622ed0d1c304ec49bc3ff6807/commands/init/fileGenerator.ts#L16-L18

I'd suggest you to change it to:

```ts
const sourceDirectory = path.resolve(path.fromFileUrl(import.meta.url)), 'template', this.runtime, this.language)
const destinationDirectory = path.resolve(Deno.cwd(), this.dirname)
```

It's more clean clossplatform way for resolving paths.

But it's not fixin issue discussed in telegram, when library used not installed, by url.

**Comment by code-withAshish** [comment]
okay thanks for bringing this up, and yes i am working on the  issue that we disussed in telegram.

**Comment by code-withAshish** [comment]
This issue is closed now i guess.
